{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 03/06/2024 15:32:51.630
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: com.microsoft.sqlserver.jdbc.SQLServerDriver
stackTrace: java.lang.ClassNotFoundException: com.microsoft.sqlserver.jdbc.SQLServerDriverat java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)at java.base/java.lang.Class.forName0(Native Method)at java.base/java.lang.Class.forName(Class.java:375)at org.example.connection.Conexao.<clinit>(Conexao.java:39)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:20)
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 03/06/2024 15:36:30.670
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: Access denied for user 'root'@'131.72.61.70' (using password: YES)
stackTrace: java.sql.SQLException: Access denied for user 'root'@'131.72.61.70' (using password: YES)at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionMYSQL.getConexaoEspecifica(ConnectionMYSQL.java:13)at org.example.connection.Conexao.<clinit>(Conexao.java:41)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:20)
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 03/06/2024 15:38:17.349
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: Access denied for user 'root'@'131.72.61.70' (using password: YES)
stackTrace: java.sql.SQLException: Access denied for user 'root'@'131.72.61.70' (using password: YES)at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionMYSQL.getConexaoEspecifica(ConnectionMYSQL.java:13)at org.example.connection.Conexao.<clinit>(Conexao.java:34)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:20)
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 03/06/2024 15:40:15.603
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: Access denied for user 'root'@'131.72.61.70' (using password: YES)
stackTrace: java.sql.SQLException: Access denied for user 'root'@'131.72.61.70' (using password: YES)at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionMYSQL.getConexaoEspecifica(ConnectionMYSQL.java:13)at org.example.connection.Conexao.<clinit>(Conexao.java:34)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:20)
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 03/06/2024 15:41:59.231
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: Access denied for user 'root'@'131.72.61.70' (using password: YES)
stackTrace: java.sql.SQLException: Access denied for user 'root'@'131.72.61.70' (using password: YES)at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionMYSQL.getConexaoEspecifica(ConnectionMYSQL.java:13)at org.example.connection.Conexao.<clinit>(Conexao.java:34)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:20)
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 03/06/2024 15:42:34.290
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: Access denied for user 'root'@'131.72.61.70' (using password: YES)
stackTrace: java.sql.SQLException: Access denied for user 'root'@'131.72.61.70' (using password: YES)at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionMYSQL.getConexaoEspecifica(ConnectionMYSQL.java:13)at org.example.connection.Conexao.<clinit>(Conexao.java:34)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:20)
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 03/06/2024 15:48:58.020
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: Access denied for user 'root'@'131.72.61.70' (using password: YES)
stackTrace: java.sql.SQLException: Access denied for user 'root'@'131.72.61.70' (using password: YES)at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionMYSQL.getConexaoEspecifica(ConnectionMYSQL.java:13)at org.example.connection.Conexao.<clinit>(Conexao.java:34)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:20)
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 03/06/2024 15:52:25.985
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: Falha na conexão TCP/IP com o host 52.200.17.70/sisguard, porta 1433. Erro: "52.200.17.70/sisguard. Verifique as propriedades da conexão. Verifique se uma instância do SQL Server está sendo executada no host e se está aceitando conexões TCP/IP na porta. Verifique se as conexões TCP na porta não foram bloqueadas por um firewall.".
stackTrace: com.microsoft.sqlserver.jdbc.SQLServerException: Falha na conexão TCP/IP com o host 52.200.17.70/sisguard, porta 1433. Erro: "52.200.17.70/sisguard. Verifique as propriedades da conexão. Verifique se uma instância do SQL Server está sendo executada no host e se está aceitando conexões TCP/IP na porta. Verifique se as conexões TCP na porta não foram bloqueadas por um firewall.".at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237)at com.microsoft.sqlserver.jdbc.SQLServerException.ConvertConnectExceptionToSQLServerException(SQLServerException.java:288)at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2720)at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:761)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3180)at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionSQLSERVER.getConexaoEspecifica(ConnectionSQLSERVER.java:13)at org.example.connection.Conexao.<clinit>(Conexao.java:35)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:20)
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 03/06/2024 15:54:51.245
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: Falha na conexão TCP/IP com o host 52.200.17.70/sisguard, porta 1433. Erro: "52.200.17.70/sisguard. Verifique as propriedades da conexão. Verifique se uma instância do SQL Server está sendo executada no host e se está aceitando conexões TCP/IP na porta. Verifique se as conexões TCP na porta não foram bloqueadas por um firewall.".
stackTrace: com.microsoft.sqlserver.jdbc.SQLServerException: Falha na conexão TCP/IP com o host 52.200.17.70/sisguard, porta 1433. Erro: "52.200.17.70/sisguard. Verifique as propriedades da conexão. Verifique se uma instância do SQL Server está sendo executada no host e se está aceitando conexões TCP/IP na porta. Verifique se as conexões TCP na porta não foram bloqueadas por um firewall.".at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237)at com.microsoft.sqlserver.jdbc.SQLServerException.ConvertConnectExceptionToSQLServerException(SQLServerException.java:288)at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2720)at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:761)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3180)at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionSQLSERVER.getConexaoEspecifica(ConnectionSQLSERVER.java:13)at org.example.connection.Conexao.<clinit>(Conexao.java:35)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:20)
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 03/06/2024 15:57:17.069
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: A cadeia de conexão contém um nome ou valor formado incorretamente.
stackTrace: com.microsoft.sqlserver.jdbc.SQLServerException: A cadeia de conexão contém um nome ou valor formado incorretamente.at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237)at com.microsoft.sqlserver.jdbc.Util.parseUrl(Util.java:512)at com.microsoft.sqlserver.jdbc.SQLServerDriver.parseAndMergeProperties(SQLServerDriver.java:948)at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:933)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionSQLSERVER.getConexaoEspecifica(ConnectionSQLSERVER.java:13)at org.example.connection.Conexao.<clinit>(Conexao.java:35)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:20)
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 03/06/2024 15:57:51.561
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: O driver não pôde estabelecer uma conexão segura com o SQL Server usando a criptografia SSL. Erro: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:6f29d5de-caa2-47d6-ad7b-72fd7776aa5e
stackTrace: com.microsoft.sqlserver.jdbc.SQLServerException: O driver não pôde estabelecer uma conexão segura com o SQL Server usando a criptografia SSL. Erro: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:6f29d5de-caa2-47d6-ad7b-72fd7776aa5eat com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:3680)at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:2113)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3204)at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionSQLSERVER.getConexaoEspecifica(ConnectionSQLSERVER.java:13)at org.example.connection.Conexao.<clinit>(Conexao.java:35)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:20)Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested targetat java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:2021)... 11 moreCaused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested targetat java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)at java.base/sun.security.validator.Validator.validate(Validator.java:264)at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:242)at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:113)at com.microsoft.sqlserver.jdbc.TDSChannel$HostNameOverrideX509TrustManager.checkServerTrusted(IOBuffer.java:1702)at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1441)at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)... 23 moreCaused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested targetat java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)... 30 more
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 03/06/2024 16:02:12.853
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: O driver não pôde estabelecer uma conexão segura com o SQL Server usando a criptografia SSL. Erro: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:a99286fc-de87-431c-8750-4942c4083ae5
stackTrace: com.microsoft.sqlserver.jdbc.SQLServerException: O driver não pôde estabelecer uma conexão segura com o SQL Server usando a criptografia SSL. Erro: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:a99286fc-de87-431c-8750-4942c4083ae5at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:3680)at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:2113)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3204)at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionSQLSERVER.getConexaoEspecifica(ConnectionSQLSERVER.java:13)at org.example.connection.Conexao.<clinit>(Conexao.java:35)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:20)Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested targetat java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:2021)... 11 moreCaused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested targetat java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)at java.base/sun.security.validator.Validator.validate(Validator.java:264)at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:242)at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:113)at com.microsoft.sqlserver.jdbc.TDSChannel$HostNameOverrideX509TrustManager.checkServerTrusted(IOBuffer.java:1702)at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1441)at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)... 23 moreCaused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested targetat java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)... 30 more
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 03/06/2024 16:07:23.415
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: O driver não pôde estabelecer uma conexão segura com o SQL Server usando a criptografia SSL. Erro: "Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty". ClientConnectionId:a5fd8e37-7288-4dbe-8395-9bffcfe404ea
stackTrace: com.microsoft.sqlserver.jdbc.SQLServerException: O driver não pôde estabelecer uma conexão segura com o SQL Server usando a criptografia SSL. Erro: "Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty". ClientConnectionId:a5fd8e37-7288-4dbe-8395-9bffcfe404eaat com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:3680)at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:2113)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3204)at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionSQLSERVER.getConexaoEspecifica(ConnectionSQLSERVER.java:13)at org.example.connection.Conexao.<clinit>(Conexao.java:35)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:23)Caused by: javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-emptyat java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1708)at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:470)at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:2021)... 11 moreCaused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-emptyat java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:101)at java.base/sun.security.validator.Validator.getInstance(Validator.java:181)at java.base/sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:309)at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:183)at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:198)at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:113)at com.microsoft.sqlserver.jdbc.TDSChannel$HostNameOverrideX509TrustManager.checkServerTrusted(IOBuffer.java:1702)at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1441)at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)... 13 moreCaused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-emptyat java.base/java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)at java.base/java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)at java.base/java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:98)... 31 more
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 03/06/2024 16:13:21.245
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: O driver não pôde estabelecer uma conexão segura com o SQL Server usando a criptografia SSL. Erro: "Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty". ClientConnectionId:58bbc69d-2c64-4166-bfe5-7b772497b00c
stackTrace: com.microsoft.sqlserver.jdbc.SQLServerException: O driver não pôde estabelecer uma conexão segura com o SQL Server usando a criptografia SSL. Erro: "Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty". ClientConnectionId:58bbc69d-2c64-4166-bfe5-7b772497b00cat com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:3680)at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:2113)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3204)at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionSQLSERVER.getConexaoEspecifica(ConnectionSQLSERVER.java:13)at org.example.connection.Conexao.<clinit>(Conexao.java:35)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:23)Caused by: javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-emptyat java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1708)at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:470)at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:2021)... 11 moreCaused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-emptyat java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:101)at java.base/sun.security.validator.Validator.getInstance(Validator.java:181)at java.base/sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:309)at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:183)at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:198)at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:113)at com.microsoft.sqlserver.jdbc.TDSChannel$HostNameOverrideX509TrustManager.checkServerTrusted(IOBuffer.java:1702)at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1441)at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)... 13 moreCaused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-emptyat java.base/java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)at java.base/java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)at java.base/java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:98)... 31 more
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 03/06/2024 16:23:16.546
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: O driver não pôde estabelecer uma conexão segura com o SQL Server usando a criptografia SSL. Erro: "Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty". ClientConnectionId:874ed988-4cd9-40f0-b31c-0710fd79b2f4
stackTrace: com.microsoft.sqlserver.jdbc.SQLServerException: O driver não pôde estabelecer uma conexão segura com o SQL Server usando a criptografia SSL. Erro: "Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty". ClientConnectionId:874ed988-4cd9-40f0-b31c-0710fd79b2f4at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:3680)at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:2113)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3204)at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionSQLSERVER.getConexaoEspecifica(ConnectionSQLSERVER.java:13)at org.example.connection.Conexao.<clinit>(Conexao.java:35)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:23)Caused by: javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-emptyat java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1708)at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:470)at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:2021)... 11 moreCaused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-emptyat java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:101)at java.base/sun.security.validator.Validator.getInstance(Validator.java:181)at java.base/sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:309)at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:183)at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:198)at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:113)at com.microsoft.sqlserver.jdbc.TDSChannel$HostNameOverrideX509TrustManager.checkServerTrusted(IOBuffer.java:1702)at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1441)at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)... 13 moreCaused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-emptyat java.base/java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)at java.base/java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)at java.base/java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:98)... 31 more
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 03/06/2024 16:29:12.550
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: O driver não pôde estabelecer uma conexão segura com o SQL Server usando a criptografia SSL. Erro: "Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty". ClientConnectionId:0e8e07d5-85ed-4b7b-8fd8-e93850552245
stackTrace: com.microsoft.sqlserver.jdbc.SQLServerException: O driver não pôde estabelecer uma conexão segura com o SQL Server usando a criptografia SSL. Erro: "Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty". ClientConnectionId:0e8e07d5-85ed-4b7b-8fd8-e93850552245at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:3680)at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:2113)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3204)at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionSQLSERVER.getConexaoEspecifica(ConnectionSQLSERVER.java:13)at org.example.connection.Conexao.<clinit>(Conexao.java:35)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:23)Caused by: javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-emptyat java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1708)at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:470)at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:2021)... 11 moreCaused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-emptyat java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:101)at java.base/sun.security.validator.Validator.getInstance(Validator.java:181)at java.base/sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:309)at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:183)at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:198)at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:113)at com.microsoft.sqlserver.jdbc.TDSChannel$HostNameOverrideX509TrustManager.checkServerTrusted(IOBuffer.java:1702)at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1441)at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)... 13 moreCaused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-emptyat java.base/java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)at java.base/java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)at java.base/java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:98)... 31 more
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 04/06/2024 10:20:46.404
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: O driver não pôde estabelecer uma conexão segura com o SQL Server usando a criptografia SSL. Erro: "Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty". ClientConnectionId:164015d8-d0d0-4279-86bc-a0034697045e
stackTrace: com.microsoft.sqlserver.jdbc.SQLServerException: O driver não pôde estabelecer uma conexão segura com o SQL Server usando a criptografia SSL. Erro: "Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty". ClientConnectionId:164015d8-d0d0-4279-86bc-a0034697045eat com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:3680)at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:2113)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3204)at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionSQLSERVER.getConexaoEspecifica(ConnectionSQLSERVER.java:13)at org.example.connection.Conexao.<clinit>(Conexao.java:35)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:23)Caused by: javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-emptyat java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1708)at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:470)at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:2021)... 11 moreCaused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-emptyat java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:101)at java.base/sun.security.validator.Validator.getInstance(Validator.java:181)at java.base/sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:309)at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:183)at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:198)at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:113)at com.microsoft.sqlserver.jdbc.TDSChannel$HostNameOverrideX509TrustManager.checkServerTrusted(IOBuffer.java:1702)at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1441)at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)... 13 moreCaused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-emptyat java.base/java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)at java.base/java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)at java.base/java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:98)... 31 more
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 04/06/2024 11:01:07.993
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: Cannot open database "sisguard" requested by the login. The login failed. ClientConnectionId:7f872eb6-b663-4bac-811a-fa37e42def3c
stackTrace: com.microsoft.sqlserver.jdbc.SQLServerException: Cannot open database "sisguard" requested by the login. The login failed. ClientConnectionId:7f872eb6-b663-4bac-811a-fa37e42def3cat com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:299)at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:132)at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6162)at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4785)at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4723)at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7785)at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3793)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3233)at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionSQLSERVER.getConexaoEspecifica(ConnectionSQLSERVER.java:15)at org.example.connection.Conexao.<clinit>(Conexao.java:35)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:23)
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 04/06/2024 11:14:25.681
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: Cannot open database "sisguard" requested by the login. The login failed. ClientConnectionId:b142f337-293d-4df4-8fbc-86da49f477f0
stackTrace: com.microsoft.sqlserver.jdbc.SQLServerException: Cannot open database "sisguard" requested by the login. The login failed. ClientConnectionId:b142f337-293d-4df4-8fbc-86da49f477f0at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:299)at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:132)at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6162)at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4785)at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4723)at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7785)at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3793)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3233)at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionSQLSERVER.getConexaoEspecifica(ConnectionSQLSERVER.java:15)at org.example.connection.Conexao.<clinit>(Conexao.java:35)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:23)
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 04/06/2024 11:27:52.327
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: Cannot open database "sisguard" requested by the login. The login failed. ClientConnectionId:a1ec27a3-2571-4819-9f5b-a07c210b422d
stackTrace: com.microsoft.sqlserver.jdbc.SQLServerException: Cannot open database "sisguard" requested by the login. The login failed. ClientConnectionId:a1ec27a3-2571-4819-9f5b-a07c210b422dat com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:299)at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:132)at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6162)at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4785)at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4723)at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7785)at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3793)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3233)at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionSQLSERVER.getConexaoEspecifica(ConnectionSQLSERVER.java:15)at org.example.connection.Conexao.<clinit>(Conexao.java:35)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:23)
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 04/06/2024 11:28:27.747
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: Cannot open database "sisguard" requested by the login. The login failed. ClientConnectionId:2ca27a6d-3372-4200-a246-5d7ab1227eef
stackTrace: com.microsoft.sqlserver.jdbc.SQLServerException: Cannot open database "sisguard" requested by the login. The login failed. ClientConnectionId:2ca27a6d-3372-4200-a246-5d7ab1227eefat com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:299)at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:132)at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6162)at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4785)at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4723)at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7785)at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3793)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3233)at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionSQLSERVER.getConexaoEspecifica(ConnectionSQLSERVER.java:15)at org.example.connection.Conexao.<clinit>(Conexao.java:35)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:23)
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 04/06/2024 13:09:42.575
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: Cannot open database "sisguard" requested by the login. The login failed. ClientConnectionId:c79ba3fa-6be0-4e6d-8e5a-efe6716ea4c1
stackTrace: com.microsoft.sqlserver.jdbc.SQLServerException: Cannot open database "sisguard" requested by the login. The login failed. ClientConnectionId:c79ba3fa-6be0-4e6d-8e5a-efe6716ea4c1at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:299)at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:132)at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6162)at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4785)at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4723)at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7785)at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3793)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3233)at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionSQLSERVER.getConexaoEspecifica(ConnectionSQLSERVER.java:15)at org.example.connection.Conexao.<clinit>(Conexao.java:35)at org.example.login.Usuario.validarUser(Usuario.java:17)at org.example.Main.main(Main.java:23)
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 04/06/2024 13:10:46.494
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: Cannot open database "sisguard" requested by the login. The login failed. ClientConnectionId:76beb7e1-b0d1-4263-945e-dc18e6cb0d42
stackTrace: com.microsoft.sqlserver.jdbc.SQLServerException: Cannot open database "sisguard" requested by the login. The login failed. ClientConnectionId:76beb7e1-b0d1-4263-945e-dc18e6cb0d42at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:299)at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:132)at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6162)at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4785)at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4723)at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7785)at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3793)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3233)at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionSQLSERVER.getConexaoEspecifica(ConnectionSQLSERVER.java:15)at org.example.connection.Conexao.<clinit>(Conexao.java:35)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:23)
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 04/06/2024 14:27:14.654
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: Cannot open database "sisguard" requested by the login. The login failed. ClientConnectionId:3b7f7b21-3425-4870-8614-221e49fa474a
stackTrace: com.microsoft.sqlserver.jdbc.SQLServerException: Cannot open database "sisguard" requested by the login. The login failed. ClientConnectionId:3b7f7b21-3425-4870-8614-221e49fa474aat com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:299)at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:132)at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6162)at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4785)at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4723)at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7785)at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3793)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3233)at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionSQLSERVER.getConexaoEspecifica(ConnectionSQLSERVER.java:15)at org.example.connection.Conexao.<clinit>(Conexao.java:35)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:23)
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 04/06/2024 14:31:07.580
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: Cannot open database "sisguard" requested by the login. The login failed. ClientConnectionId:f2ffcbbb-8161-45b2-be05-f56a00b96abf
stackTrace: com.microsoft.sqlserver.jdbc.SQLServerException: Cannot open database "sisguard" requested by the login. The login failed. ClientConnectionId:f2ffcbbb-8161-45b2-be05-f56a00b96abfat com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:299)at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:132)at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6162)at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4785)at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4723)at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7785)at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3793)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3233)at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionSQLSERVER.getConexaoEspecifica(ConnectionSQLSERVER.java:15)at org.example.connection.Conexao.<clinit>(Conexao.java:35)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:23)
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 04/06/2024 14:35:25.271
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: Cannot open database "sisguard" requested by the login. The login failed. ClientConnectionId:71b0c846-44f1-43f8-8360-7ecf59dc411c
stackTrace: com.microsoft.sqlserver.jdbc.SQLServerException: Cannot open database "sisguard" requested by the login. The login failed. ClientConnectionId:71b0c846-44f1-43f8-8360-7ecf59dc411cat com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:299)at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:132)at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6162)at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4785)at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4723)at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7785)at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3793)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3233)at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionSQLSERVER.getConexaoEspecifica(ConnectionSQLSERVER.java:15)at org.example.connection.Conexao.<clinit>(Conexao.java:35)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:23)
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 04/06/2024 14:53:57.903
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: Cannot open database "sisguard" requested by the login. The login failed. ClientConnectionId:542f6d9a-91a8-42dd-994a-e09a178c157b
stackTrace: com.microsoft.sqlserver.jdbc.SQLServerException: Cannot open database "sisguard" requested by the login. The login failed. ClientConnectionId:542f6d9a-91a8-42dd-994a-e09a178c157bat com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:299)at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:132)at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6162)at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4785)at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4723)at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7785)at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3793)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3233)at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionSQLSERVER.getConexaoEspecifica(ConnectionSQLSERVER.java:15)at org.example.connection.Conexao.<clinit>(Conexao.java:35)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:23)
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 04/06/2024 20:35:03.310
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: Cannot open database "sisguard" requested by the login. The login failed. ClientConnectionId:d81614bd-7304-4294-83ea-840e1a36d603
stackTrace: com.microsoft.sqlserver.jdbc.SQLServerException: Cannot open database "sisguard" requested by the login. The login failed. ClientConnectionId:d81614bd-7304-4294-83ea-840e1a36d603at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:299)at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:132)at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6162)at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4785)at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4723)at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7785)at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3793)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3233)at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionSQLSERVER.getConexaoEspecifica(ConnectionSQLSERVER.java:15)at org.example.connection.Conexao.<clinit>(Conexao.java:35)at org.example.login.Usuario.validarUser(Usuario.java:16)at org.example.Main.main(Main.java:23)
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 04/06/2024 22:35:52.465
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: Falha na conexão TCP/IP com o host 52.200.17.70, porta 1433. Erro: "Connect timed out. Verifique as propriedades da conexão. Verifique se uma instância do SQL Server está sendo executada no host e se está aceitando conexões TCP/IP na porta. Verifique se as conexões TCP na porta não foram bloqueadas por um firewall.".
stackTrace: com.microsoft.sqlserver.jdbc.SQLServerException: Falha na conexão TCP/IP com o host 52.200.17.70, porta 1433. Erro: "Connect timed out. Verifique as propriedades da conexão. Verifique se uma instância do SQL Server está sendo executada no host e se está aceitando conexões TCP/IP na porta. Verifique se as conexões TCP na porta não foram bloqueadas por um firewall.".at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237)at com.microsoft.sqlserver.jdbc.SQLServerException.ConvertConnectExceptionToSQLServerException(SQLServerException.java:288)at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2720)at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:761)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3180)at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionSQLSERVER.getConexaoEspecifica(ConnectionSQLSERVER.java:15)at org.example.connection.Conexao.<clinit>(Conexao.java:35)at org.example.login.Usuario.validarUser(Usuario.java:18)at org.example.Main.main(Main.java:23)
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-HTJU258
Data: 05/06/2024 12:42:33.365
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
stackTrace: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failureThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:175)at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionMYSQL.getConexaoEspecifica(ConnectionMYSQL.java:13)at org.example.connection.Conexao.<clinit>(Conexao.java:34)at org.example.login.Usuario.validarUser(Usuario.java:18)at org.example.Main.main(Main.java:23)Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failureThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150)at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:166)at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)at com.mysql.cj.NativeSession.connect(NativeSession.java:121)at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:945)at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:815)... 9 moreCaused by: java.net.ConnectException: Connection timed out: connectat java.base/sun.nio.ch.Net.connect0(Native Method)at java.base/sun.nio.ch.Net.connect(Net.java:579)at java.base/sun.nio.ch.Net.connect(Net.java:568)at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)at java.base/java.net.Socket.connect(Socket.java:633)at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:153)at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)... 12 more
}
