{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 11/06/2024 10:08:34.273
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
stackTrace: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failureThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:175)at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionMYSQL.getConexaoEspecifica(ConnectionMYSQL.java:13)at org.example.connection.Conexao.<clinit>(Conexao.java:34)at org.example.login.Usuario.validarUser(Usuario.java:18)at org.example.Main.main(Main.java:24)Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failureThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150)at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:166)at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)at com.mysql.cj.NativeSession.connect(NativeSession.java:121)at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:945)at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:815)... 9 moreCaused by: java.net.ConnectException: Connection timed out: connectat java.base/sun.nio.ch.Net.connect0(Native Method)at java.base/sun.nio.ch.Net.connect(Net.java:579)at java.base/sun.nio.ch.Net.connect(Net.java:568)at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)at java.base/java.net.Socket.connect(Socket.java:633)at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:153)at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)... 12 more
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 11/06/2024 10:14:01.834
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: Access denied for user 'root'@'131.72.61.70' (using password: YES)
stackTrace: java.sql.SQLException: Access denied for user 'root'@'131.72.61.70' (using password: YES)at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionMYSQL.getConexaoEspecifica(ConnectionMYSQL.java:13)at org.example.connection.Conexao.<clinit>(Conexao.java:34)at org.example.login.Usuario.validarUser(Usuario.java:18)at org.example.Main.main(Main.java:24)
}
{
sistema Operacional: Windows
arquitetura: 64
hostname: DESKTOP-37HPSIQ
Data: 11/06/2024 10:15:12.543
logLevel: ERROR
statusCode: 503
idMaquina: 
mensagem: Erro ao conectar ao banco de dados: Access denied for user 'root'@'131.72.61.70' (using password: YES)
stackTrace: java.sql.SQLException: Access denied for user 'root'@'131.72.61.70' (using password: YES)at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)at org.example.connection.ConnectionMYSQL.getConexaoEspecifica(ConnectionMYSQL.java:13)at org.example.connection.Conexao.<clinit>(Conexao.java:34)at org.example.login.Usuario.validarUser(Usuario.java:18)at org.example.Main.main(Main.java:24)
}
